FROM node:lts-alpine AS builder
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run type-check
RUN npm run build
RUN npm prune --production

FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/node_modules/ ./node_modules/
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/ ./.next/
COPY --from=builder /app/next.config.js ./next.config.js
EXPOSE 3000
CMD ["node_modules/.bin/next", "start"]
