name: Analytics

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run
        run: nohup npm start &

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          runs: 3
          urls: |
            http://localhost:3000/
          temporaryPublicStorage: true